### ISSUE TITLE
Test Fails

### ISSUE THREAD

**Issue by thiloshon** [bd-R/bdchecks#37]
There are few test files while running RCMCheck in master.

@Martis6 Please take a look.

![Capture](https://user-images.githubusercontent.com/17028697/132996036-f2141ce9-d6f5-4393-b164-de9611df135c.PNG)

**Comment by Martis6** [comment]
This issue is [solved](https://github.com/bd-R/bdchecks/commit/8531287b7cc00b32cd4d175583cbb907c3f0c34f) (well kinda) in dev branch. I explained it to @tom-gu a while ago.

Basically in family data check calling `taxize::classification()` on "Pongidae" gives "Hominidae", which is synonymous term and this was changed during the last year. Future gbif taxonomy changes like that maybe should be addressed somehow, since similar thing could happen again in the future. And kingdom data check warnings are solved as well.

**Comment by tom-gu** [comment]
Solved on dev branch
